// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/vws.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// optimize_hybrid_rcpp
Rcpp::List optimize_hybrid_rcpp(const Rcpp::Function& f, double init, double lower, double upper, bool maximize, unsigned maxiter);
RcppExport SEXP _vws_optimize_hybrid_rcpp(SEXP fSEXP, SEXP initSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP maximizeSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    Rcpp::traits::input_parameter< unsigned >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_hybrid_rcpp(f, init, lower, upper, maximize, maxiter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vws_optimize_hybrid_rcpp", (DL_FUNC) &_vws_optimize_hybrid_rcpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_vws(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
