# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rectangular transformation
#'
#' A transformation from Euclidean to a rectangle in \eqn{\mathbb{R}^n}, and
#' its inverse transformation.
#'
#' @param x A point in \eqn{\mathbb{R}^{d}}.
#' @param z A point in the rectangle \eqn{[a_1,b_1] \times \cdots \times [a_d,b_d]}.
#' @param a A vector \eqn{(a_1, \ldots, a_d)}, Elements may be \code{-Inf}.
#' @param b A vector \eqn{(b_1, \ldots, b_d)}, Elements may be \code{Inf}.
#'
#' @examples
#' x = seq(-1, 1, length.out = 3)
#' a = rep(0, 3)
#' b = rep(1, 3)
#' z = inv_rect(x, a, b)
#' rect(z, a, b)
#'
#' a = c(-Inf, 0, -Inf)
#' b = c(Inf, 1, Inf)
#' z = inv_rect(x, a, b)
#' rect(z, a, b)
#'
#' @name rect
#' @export
NULL

#' @name rect
#' @export
NULL

#' Optimize Hybrid
#'
#' @param f TBD
#' @param init TBD
#' @param lower TBD
#' @param upper TBD
#' @param maximize TBD
#' @param maxiter TBD
#'
#' @export
optimize_hybrid <- function(f, init, lower, upper, maximize, maxiter = 100000L) {
    .Call(`_vws_optimize_hybrid_rcpp`, f, init, lower, upper, maximize, maxiter)
}

